### PR TITLE
A series of improvements

### PR DESCRIPTION
**Pull request by flambert**
Here is a series of small improvements for your consideration

### CODE REVIEW

**Comment by dainkaplan** [comment]
I just saw this; sorry! All look good except the last for not setting the shadow. What's the reasoning behind that?

**Comment by flambert** [comment]
You can set it yourself on the .layer if you need it. In the moment it did not seem necessary to add properties to do that.

I should have moved it to the init method.
It shouldn't be in the drawInRect: method.

**Comment by dainkaplan** [comment]
Fair enough. I'll merge this, then.

**Comment by flambert** [comment]
Thanks, but like I said, I think the layer shadow code should be moved to init to keep the current visual aspect of the chart (it does look good with it). It's a really nice component.

**Comment by dainkaplan** [comment]
Yeah, I'll add that to init in a separate commit shortly. Thanks for the fixes/additions!

**Pull request merged**
